### ISSUE TITLE
Future development of AllAccounts extenson and comparison with Multifox 3.x

### ISSUE THREAD

**Issue by MurzNN** [hultmann/allaccounts#15]
I see that you release 3.0 version of Multifox plugin later that last AllAccounts 2.1 version on page https://getmultifox.com/all/

Is Multifox 3.x evolution of AllAccounts extension or developing AllAccounts stay separately of Multifox? If yes - can you describe differences and goals for this 2 projects? 

Because me and new users can't understand which version from https://getmultifox.com/all/ are fresh and must be selected for everyday usage.

And can you add release dates of each release on page https://getmultifox.com/all/ for quick understanding which release are last? Thanks.

**Comment by hultmann** [comment]
I think I'll move AllAccounts to a different page.

> Is Multifox 3.x evolution of AllAccounts extension or developing AllAccounts stay separately of Multifox? If yes - can you describe differences and goals for this 2 projects? 

They are different projects. AllAccounts is a kind of prototype, don't expect to see it on AMO. Multifox is targeted to actual users.

**Comment by MurzNN** [comment]
Thanks for quick reply. Before Multifox 3.x I use AllAccounts and all works well on most of sites. 

But I have some problems with sites, that have auth on 3-level domains (subdomain.domain.com). Also I have problems with posting comments on blogs like http://webmaster.ya.ru/ that have authentification on other domain https://passport.yandex.ru/  I see new version of Multifox 3.x and switch to it (thinking that this is new version of AllAccounts). As result - Multifox 3.x don't have those problems, but interface is usability is worse that in AllAccounts. 

So idea and interface of AllAccoutns is much better that in Multifox, because it store profiles per-site, not globally like Multifox. But I can't use AllAccounts every day because it now working on some sites.

Can you describe future plans of AllAccounts? Will you plan to improve functionality of AllAccounts (add whitelist mode, fix support for subdomains, etc) and I can hope and wait? Or AllAccounts will stay as prototype and I must seletc Multifox 3.x for everyday usage? Thanks.

What I must select - switc

**Comment by hultmann** [comment]
AllAccounts will stay as prototype. Well, I'm willing to try fixing these bugs since I use AllAccounts (at least multiple domain logins etc).

But I can't give you too much hope, I'm about to start other Mozilla-related projects which will take a lot of time.

**Comment by MurzNN** [comment]
Ok, I will wait for new releases of AllAccounts with fixing multiple domain logins, whitelist mode and subdomains, but at now will use Multifox 3.x. Can you describe differences of AllAccounts and Multifox on https://getmultifox.com/all/  page and add release dates?

**Comment by hultmann** [comment]
I added some release dates (the ones I can verify).
